# Generated by Django 5.0.6 on 2024-11-18 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0002_student_delete_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Name',
            new_name='name',
        ),
    ]
