# Generated by Django 5.0.6 on 2024-11-18 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0005_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
