# Generated by Django 5.0.6 on 2024-11-18 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0006_delete_customer'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='student',
            table='student',
        ),
    ]
