# Generated by Django 5.0.6 on 2024-11-18 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0009_alter_student_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='student',
            table='Student',
        ),
    ]
