# Generated by Django 5.0.6 on 2024-11-18 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0011_alter_student_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='student',
            table=None,
        ),
    ]
