# Generated by Django 5.0.6 on 2024-11-19 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0015_todo_delete_add_work'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
