# Generated by Django 5.0.6 on 2024-11-20 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0018_rename_name_todo_todo_name'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='todo',
            table='todo_list',
        ),
    ]
